import { BasePayload } from 'payload'
import { uploadMedia, uploadMediaBatch, UploadedMedia } from '../utils/media'

export const seedLandingPage = async (payload: BasePayload) => {
  const heroVideo = await uploadMedia(payload, 'landingPage/hero-bg.mp4', 'Hero Video')

  const portfolioData = [
    { filename: 'portfolio (1).png', alt: 'Portfolio' },
    { filename: 'portfolio (2).png', alt: 'Portfolio' },
    { filename: 'portfolio (3).png', alt: 'Portfolio' },
    { filename: 'portfolio (4).png', alt: 'Portfolio' },
    { filename: 'portfolio (5).png', alt: 'Portfolio' },
    { filename: 'portfolio (6).png', alt: 'Portfolio' },
    { filename: 'portfolio (7).png', alt: 'Portfolio' },
  ]
  const portfolioMedia: UploadedMedia[] = await uploadMediaBatch(
    payload,
    'landingPage',
    portfolioData,
  )

  const buyoutData = [
    { filename: 'buyout (1).svg', alt: 'Buyout' },
    { filename: 'buyout (2).svg', alt: 'Buyout' },
    { filename: 'buyout (3).svg', alt: 'Buyout' },
    { filename: 'buyout (4).svg', alt: 'Buyout' },
  ]
  const buyoutMedia: UploadedMedia[] = await uploadMediaBatch(payload, 'landingPage', buyoutData)

  await payload.updateGlobal({
    slug: 'landingPage',
    data: {
      hero: {
        title: 'ready to go big?',
        subtitle: 'Empowering brands through creativity',
        sessions: '24B+',
        players: '1B+',
        hours: '1B+',
        backgroundVideo: heroVideo ? heroVideo.id : undefined,
      },
      portfolio: {
        title: "We've helped scale",
        items: portfolioMedia.slice(0, 7).map((m) => ({ href: 'https://www.google.com', image: (m.id as number) })),
      },
      hits: { title: 'Our top hits' },
      cases: { title: 'Case studies' },
      buyout: {
        title: 'STRATEGIC GAME BUYOUT',
        items: [
          {
            name: 'Full Game Acquisition',
            description:
              'We purchase your Roblox game outright, offering a competitive upfront payment.',
            icon: buyoutMedia[0] ? buyoutMedia[0].id : undefined,
          },
          {
            name: 'Expert Development & Marketing',
            description:
              'Our experienced team takes over development, marketing, and ongoing optimization.',
            icon: buyoutMedia[1] ? buyoutMedia[1].id : undefined,
          },
          {
            name: 'Revenue Sharing',
            description: 'You will benefit from continued revenue generated by your game.',
            icon: buyoutMedia[2] ? buyoutMedia[2].id : undefined,
          },
          {
            name: 'Hassle-Free Transition',
            description:
              'Sit back and relax! We handle everything from the sale to future management, allowing you to focus on your next big idea.',
            icon: buyoutMedia[3] ? buyoutMedia[3].id : undefined,
          },
        ],
      },
    },
  })
}
